### ISSUE TITLE
Usage questions

### ISSUE THREAD

**Issue by ayahnenko** [flauwekeul/honeycomb#2]
Hello!

First, great thanks for this library. I'm making a hex-based game and really hope it will save me a lot of time on implementation.

I'm just starting to play with it and got a couple of questions, because I'm not sure I'm getting the right idea how to use it.

1. When I use Grid factory to create a rectange grid, like this:
```js
var Grid = HC.Grid({
    size: 24,
    orientation: HC.HEX_ORIENTATIONS.POINTY
});

var grid = Grid.rectangle(10, 10);
```
Now the `grid` variable is an array, but i'd expect to use it as object, i mean a container of all hexes, to be able to do smth like this:
```js 
grid.getHex(1,2,3).getNeighborsInRadius(3);
// or
grid.getHex(1,2,3).getDistanceTo(grid.getHex(5,6,7));
```
What is the right way to do this?

2. I'm testing finding hex by coordinates, using the very first hex of the grid, getting its center point and then trying to find hex by this point, like this:
```js
var Grid = HC.Grid({
    size: 24,
    orientation: HC.HEX_ORIENTATIONS.POINTY
});

var grid = Grid.rectangle(10, 10);
console.log(grid[0]);

var hex = Grid.pointToHex(grid[0].center());
console.log(hex);
```
The output of this is:
```
{ x: 0, y: 0, z: 0 }
{ x: 0, y: 1, z: -1 }
```
But i expected to see the same hex, because i'm looking by its center.
What am I doing wrong?

3) When i'm trying to get coordinates for all hexes in the grid:
```js
for (var i = 0; i < grid.length; i++) {
    console.log(grid[i].center());
}
```
I'm getting all the same results for each hex, why is this happening?
```js
{ x: 20.784609690826528, y: 24 }
{ x: 20.784609690826528, y: 24 }
{ x: 20.784609690826528, y: 24 }
{ x: 20.784609690826528, y: 24 }
...
```

Again, thank you for your work, hope you can help me =)

**Comment by aliaksei-yakhnenka** [comment]
Update. 
Oh I see that center() method is returning relative coordinates, but how do I get absolute?

**Comment by flauwekeul** [comment]
Thanks for using my library 😀 I'm still not satisfied with the API, so any ideas are very welcome.

1. `Grid.rectangle()` returns an [array of hexes](https://github.com/flauwekeul/honeycomb#gridrectangle).

If you want the neighbor of a hex, use the [`neighbor`](https://github.com/flauwekeul/honeycomb#hexneighbor) method on any of those hexes:

```js
var grid = HC.Grid({
    size: 24,
    orientation: HC.HEX_ORIENTATIONS.POINTY
});
var hexes = grid.rectangle(10, 10);
hexes[5].neighbor(); // returns the hex "East" of the 6th hex in the rectangle
```

To get the distance between 2 hexes, use the static [`Hex.distance`](https://github.com/flauwekeul/honeycomb#hexdistance) method:

```js
var grid = HC.Grid({
    size: 24,
    orientation: HC.HEX_ORIENTATIONS.POINTY
});
// grid.Hex is the factory function that created hexes with the options passed to HC.Grid on the previous line
var Hex = grid.Hex;
var hexes = grid.rectangle(10, 10);
Hex.distance(hexes[0], hexes[5]); // returns the distance (in hexes) between the first and 6th hex
```

I can imagine it's more intuitive to use the `grid` instance as the only way of doing these things. It could make the API simpler as one can just use the `grid` instance to do basically anything. I'll investigate the pros and cons of this approach!

2. To get the hex corresponding to a point in the grid, you only need to pass the point to [`grid.pointToHex()`](https://github.com/flauwekeul/honeycomb#gridpointtohex):

```js
var grid = HC.Grid({
    size: 24,
    orientation: HC.HEX_ORIENTATIONS.POINTY
});
var hex = grid.pointToHex([0, 0]); // should return a hex with coordinates { x: 0, y: 0, z: 0 }
var anotherHex = grid.pointToHex([173, 871]); // should return a hex with coordinates { x: -8, y: 24, z: -16 }
```

As you can see: `pointToHex()` returns the hex relative to the _origin_ hex (the hex with coordinates `{ x: 0, y: 0, z: 0 }`).

3. The reason you're getting the same values in that loop is because `hex.center()` returns the same value for all hexes. All hexes have the same center point **relative** to their top left point. What you're looking for is the `coordinates()` method:

```js
var hexes = grid.rectangle(10, 10);
for (var i = 0; i < hexes.length; i++) {
    console.log(hexes[i].coordinates());
}

// although I think forEach is more readable:
hexes.forEach(function(hex) {
    console.log(hex.coordinates());
});
```

Most of these things can be found in the documentation. But I can very well imagine you don't want to spend your time finding this information. I'm working on creating more and better examples. Btw, you might have missed the examples in the [examples folder](https://github.com/flauwekeul/honeycomb/blob/master/examples/views/svg/index.js).

**Comment by aliaksei-yakhnenka** [comment]
Hi, thank you for the answer.

It's true, I missed the examples. However I'm not really interested in rendering hexes in DOM/SVG, so they are not so helpful.

Don't get me wrong, I'm not too lazy to dig into documentation, it's just because my head is working my own way, and probably I had some wrong expectations.

What I need is a backend, server-side code that will work with a map/grid as a container, add some extra properties to hexes, find them by different parameters (like coordinates, being in radius from some hex, occupied by some game object, etc), use pathfinding, etc.

But it seems to me it's not really what I can find here, because the Grid doesn't know anything about hexes it creates, and the hexes themselves know nothing about the grid. And if I try to get a hex at certain point, like `Grid.pointToHex([1, 1])` i get a new instance of Hex, which doesn't have any of the extras I could've added before (like terrainType, terrainHeight, occupiedByPlayer, etc.). 

So I guess I'll say thank you one more time, for your library and your response, i can probably take some of the algorhytms from here, but it seems I'll have to make the container code myself.

Have a great day!

**Comment by flauwekeul** [comment]
One of the reasons I created this library is to separate hex/grid logic from the view. So this idea aligns perfectly with what you need: a viewless grid in memory in the backend. The features you need should definitely be included in this library. I just haven't build them yet 😬

It seems you expect calling `Grid#rectangle()` to define the borders of the grid, right? If so: why do you want this? I don't see why a viewless grid should have any borders... I can however understand calling `Grid#rectangle()` would return a rectangular bordered grid. Maybe I should change the name of that method to communicate it returns hexes 🤔

So, let's go over the functionality you need:
1. Adding custom properties to hexes makes a lot of sense and is currently not possible (only `size`, `orientation` and `origin` are supported). I'll change this to make it possible to add any property to hexes.
1. "Being in radius from some hex": not really sure what you mean by this...Do you want to know if any given hex is a neighbor of another hex? Or how far a hex is from another hex? Both should be possible already, although maybe not the way you expect...
1. Pathfinding: I was planning on adding this later (after I'm happy with a base API)...

I hope you haven't given up on honeycomb yet. I'm open to changing the API to make it more intuitive. Like yours, my head is working my own way too 🤓. The current API is the result of assumptions I made, but they might very well be off. That's why I've put extra effort in documentation to get my ideas across.

**Comment by aliaksei-yakhnenka** [comment]
Not giving up, no =)

I was using `Grid#rectangle()` to create a rectangular map for my game, which is a top-down-view kind of strategy, now looks like warcraft2 (i even use their terrain, buildings and units sprites for now :) ).

I have a square tiled map right now, but I decided that hex-based map will look more natural.

So using the `rectangle` method I was hoping to create a map like this:
```
⬢ ⬢ ⬢ ⬢ ⬢ ⬢ ⬢ ⬢ ⬢ ⬢
 ⬢ ⬢ ⬢ ⬢ ⬢ ⬢ ⬢ ⬢ ⬢ ⬢
⬢ ⬢ ⬢ ⬢ ⬢ ⬢ ⬢ ⬢ ⬢ ⬢
 ⬢ ⬢ ⬢ ⬢ ⬢ ⬢ ⬢ ⬢ ⬢ ⬢
```

And the map should definitely have borders :)

"Being in radius from some hex" - the best example is a unit having attack range of 4, it needs to get all possible targets around it, and select one by some priority.

Another example is you can build in 12 hex radius around your castle, so each time player places a building i need to check if it's there, if those hexes are not occupied, and also i need to send this to client to draw allowed building zone.

Pathfinding - I wasn't hoping to find it here, I believe it should be some separate library. I am using this one now: https://github.com/qiao/PathFinding.js, but it works only with square tiles. Actually after some digging I think it's not that hard to implement the A* myself.

**Comment by aliaksei-yakhnenka** [comment]
Also, I just created a 3x3 rectangle grid, output all coordinates and marked them on the picture with yellow color. The layout of the hexes seems strage to me, I expected to see those marked with blue color, why is this? Looks like it's mirrored and rotated, but how can I get the blue rectangle?

![image](https://cloud.githubusercontent.com/assets/5088482/26142523/90cdfae4-3ae9-11e7-8aea-5ac09c3c4c07.png)

**Comment by aliaksei-yakhnenka** [comment]
Ah, forget the last comment. 
I finally made the code that outputs the grid I need:

```js
for (var i = 0; i < grid.length; i++) {
    var pos = Grid.hexToPoint(grid[i]);
    var corners = grid[i].corners().map(function (corner) {
        return corner.add(pos);
    });

   game.add
        .graphics(0, 0)
        .lineStyle(1, 0x989898, 1)
        .drawPolygon(corners);
}
```

I'm getting closer! =)

**Comment by flauwekeul** [comment]
I'll try to get back to you today!

**Comment by ayahnenko** [comment]
Hmm that's strange.

I used honeycomb to generate a map and then exported it as json. Each hex is represented by object with x,y,z coordinates from hex.coordinates(), along with some other stuff.

Generated as before:
```js
var Grid = Honeycomb.Grid({
            size       : this.size,
            orientation: Honeycomb.HEX_ORIENTATIONS.POINTY
        });

        var hexes = Grid.rectangle(this.rows, this.cols);
```

Then i import this json into my Map class (hexes array as `this.xs`) and I have these functions there:
```js
getHexByCoordinates: function (x, y, z) {
        var key = [x, y, z].join(':');
        if (undefined === this._coordsCache[key]) {
            for (var i = 0; i < this.xs.length; i++) {
                var hex = this.xs[i];
                if (hex.x === x
                    && hex.y === y
                    && hex.z === z
                ) {
                    this._coordsCache[key] = hex;
                    break;
                }
            }
        }

        return this._coordsCache[key];
    }

getHexNeighbors: function (hex) {
        if (undefined === hex.neighbors) {
            hex.neighbors = [
                this.getHexByCoordinates(hex.x + 1, hex.y - 1, hex.z),
                this.getHexByCoordinates(hex.x + 1, hex.y, hex.z - 1),
                this.getHexByCoordinates(hex.x, hex.y - 1, hex.z + 1),
                this.getHexByCoordinates(hex.x, hex.y + 1, hex.z - 1),
                this.getHexByCoordinates(hex.x - 1, hex.y + 1, hex.z),
                this.getHexByCoordinates(hex.x - 1, hex.y, hex.z + 1)
            ].filter(function (hex) {
                return hex !== undefined;
            });
        }

        return hex.neighbors;
    }
```

But then i'm doing this:
```js
var hex = map.getHexByCoordinates(0, 0, 0);
var n = map.getHexNeighbors(hex);
map.draw(n);
```
And the result is
![image](https://cloud.githubusercontent.com/assets/5088482/26194275/89001d4c-3bc0-11e7-82ea-d6df5fd1487a.png)

Blue hexes are those from `n`

I feel like i'm missing something here about the x/y/z coordinates

**Comment by flauwekeul** [comment]
## Grid borders
I can image you'd need a border for your grid, e.g. to check if a unit moves off the map. I think `grid.rectangle()` should suffice. You could simply do something like this to check if a unit wants to move off map:

```js
var hexesOnMap = grid.rectangle(widthOfMap, heightOfMap);
var isWithinMapBorders = hexesOnMap.indexOf(hexThatUnitWantsToMoveTo) >= 0;
```

Right?

## Hex range
To check if a hex is within a radius (range) of another hex a similar trick can be used: [`grid.hexagon()`](https://github.com/flauwekeul/honeycomb#gridhexagon):

```js
grid.hexagon(3, targetHex); // returns hexes that are within 3 hexes around targetHex
```

## Incorrect 3x3 rectangle
Can you show the code that created the yellow hexes? The hexes listed in the black box don't correspond to the yellow hexes' coordinates...A few days ago I published v0.5.0 which [changed](https://github.com/flauwekeul/honeycomb/commit/d4398f6) the way to set the direction of `Grid`s shape methods (like rectangle).

## `Grid#findHex(x, y, z)` and `Hex#neighbors(hex)`
I'll add those methods 👍. That should hopefully fix your issue with getting the neighbors of a hex.

**Comment by flauwekeul** [comment]
1. I've added the **static** method [`Hex.neighbors()`](https://github.com/flauwekeul/honeycomb#hexneighbors) which accepts a hex and returns all its 6 neighboring hexes.
1. I've also added the possibility to add custom properties to the `Hex` prototype when creating a grid. So you can now do this:

```js
var grid = Honeycomb.Grid({
    size: 24,
    terrainType: 'grass'
});
var hexes = grid.rectangle(4, 4); // all hexes now have the terrainType property
```

Let me know if you need more help/features.

**Comment by ayahnenko** [comment]
Thanks for the update!

About the borders - it's ok, I can just check if there is a hex with desired coordinates to detect if object is inside the map, that's no problem.

The trick with the hexagon for getting hexes range is cool, I can use it, however it doesn't solve the main problem - it is a factory, it will return _new_ hexes with only coordinates. 
But I guess it's not that bad because I can detect hexes from my map by those coordinates.

I'm not sure what do you mean "hexes listed in the black box don't correspond to the yellow hexes' coordinates". I think I marked them correctly, by the coordinates. The black box is a screenshot of the console output. Anyway, here is the code, and the output. Tested on the latest version, 0.5.0. Works the same way as before:

```js
var Honeycomb = require('honeycomb-grid');

var Grid = Honeycomb.Grid({
    size: 24,
    orientation: Honeycomb.HEX_ORIENTATIONS.POINTY
});

var hexes = Grid.rectangle(3, 3);
hexes.forEach(function(hex, q) {
    console.log(hex);
});
```
```
{ x: 0, y: 0, z: 0 }
{ x: 1, y: 0, z: -1 }
{ x: 2, y: 0, z: -2 }
{ x: 0, y: 1, z: -1 }
{ x: 1, y: 1, z: -2 }
{ x: 2, y: 1, z: -3 }
{ x: -1, y: 2, z: -1 }
{ x: 0, y: 2, z: -2 }
{ x: 1, y: 2, z: -3 }
```

About the neighbors method - again, it's cool to have it, but still I'm going to have to convert its output to the real hexes stored in the map, so it's like i'll be having the Honeycomb with all its factories to perform all kinds of hex queries, and then search for real hex in my map, and cache results in there as well. Like my map is a storage but Honeycomb is a sort of hex math calculator. 
Maybe it's not that bad, but i'm a little worried about performance. In the game, there can be dozens of objects, each of them is updating 20 times per second, units searching for paths to other units, attack ranges detecting possible targets, visibility ranges detecting visible enemies, barracks searching for a free hex to place spawned unit, and other stuff like that.

Anyway, I think i'm getting somewhere and Honeycomb is a great help, so thank you again =)

**Comment by flauwekeul** [comment]
## Incorrect 3x3 rectangle
The hexes returned by `grid.rectangle(3, 3)` are correct. Here's a screenshot if I render them using a `Honeycomb.View` instance:

<img width="779" alt="screen shot 2017-05-19 at 09 30 30" src="https://cloud.githubusercontent.com/assets/1648809/26237578/fe58a61c-3c75-11e7-9653-2862d377e07c.png">

It's what you expect, right? So, the problem is likely in how you render the hexes to screen. I think [`Honeycomb.View`](https://github.com/flauwekeul/honeycomb#view) is too limiting in how to render hexes, so I understand you didn't use it. I thought a lot about creating some sort of generic `View` which people can use to create their own view. But twice I came to the same conclusion: that it's out of scope of Honeycomb. So, I guess I'll keep `Honeycomb.View` like it is: as a way to render hexes in a DOM node container. If people have their own rendering system (like you have), they can just use `Honeycomb.Grid`. Which brings us to our next issue:

## Mapping hexes to rendered hexes
If I understand you correctly you're looking for a easy and performant way to map _virtual_ hexes returned by a Honeycomb grid instance to _rendered_ hexes. In other words: automatically update your view (rendered hexes) when your model (virtual hexes) changes (and vice versa). I agree this problem needs solving. Libraries like React/Vue/Angular solve this problem for "regular" web apps, but a hex map is not a regular app.

I think this problem is out of scope for Honeycomb, but: I want to make it as easy as possible for developers that use Honeycomb. Once Honeycomb has a good enough API, I'm planning on making games/maps with it too, which should make it clearer to me how Honeycomb can help solve this problem. In the meantime, if you have any ideas on how to improve Honeycomb, let me know!

**Comment by ayahnenko** [comment]
## Incorrect 3x3 rectangle
Yeah, right, it's just because i was not using the `Honeycomb.View` but only took screenshot from the redblobgames, and they have different axis' layout. So that's ok, thanks for clearing this up.

## Mapping
I'm not really updating rendered hexes. Client-side will only receive the whole grid layout with all coordinates once. It will draw the grid lines and fill the map with terrain sprites using hexes center coordinates. Then it will be adding different game object sprites and move them according to data received from server.

So server needs ability to calculate objects positions, directions, velocities, distances, paths, zones, etc., so it needs to "see" and manipulate the whole map, with all the hexes and their additional data. 
And the idea is to make it as simple as 
```js
// pathfinding example
var hexSrc = map.getHexByPosition([x1, y1]);
var hexDst = map.getHexByPosition([x2, y2]);
var path = map.getPath(hexSrc, hexDst);

// unit logic example
var enemiesInRange = map.getHexByPosition(this.getPosition())
  .getHexesInRadius(this.attackRange)
  .filter(function(hex) {
    return hex.occupied 
      && hex.occupant.owner === this.enemyPlayer
      && hex.occupant.isAlive();
  }, this)
  .map(function(hex) {
    return hex.occupant;
  })
```
This is not possible with current implementation, BUT - as I said before I can totally use Honeycomb as a hex-math-computer that will do all the calculations and then I can store all the data I need in my own map container. So I guess this is what I'm going to do now :)
I will let you know if there is something useful needs to be added.

Thanks again :)

**Comment by flauwekeul** [comment]
Ah, but that is possible now 😀. As I mentioned in my [comment from last evening](https://github.com/flauwekeul/honeycomb/issues/2#issuecomment-302548293) you can now add custom properties to hexes. Just upgrade to v0.5.1. This enables the API you propose, like so:

```js
var hexSrc = grid.pointToHex([x1, y1]);
var hexDst = grid.pointToHex([x2, y2]);
// I'll implement `Grid#path()` in the future
var path = grid.path(hexSrc, hexDst);

var enemiesInRange = grid.pointToHex(this.getPosition())
    .hexagon(this.attackRange)
    .filter(function(hex) {
        return hex.isOccupied()
            && hex.occupant.owner === this.enemyPlayer
            && hex.occupant.isAlive();
    }, this)
    .map(function(hex) {
        return hex.occupant;
    })
```

Just create your grid like so:

```js
var grid = Honeycomb.Grid({
    size: 24,
    isOccupied: function isOccupied() {
        // ...
    },
    occupant: {
        owner: someOwner,
        isAlive: function isAlive() {
            // ...
        }
    }
});
```

**Comment by ayahnenko** [comment]
Yes, but, Grid#hexagon will return array of new hexes.
They wouldn't know anything about properties I assigned to hexes initially created with Grid#rectangle. So again I will have to map the results to hexes stored in the map.
And passing functions and properties to constructor is not really helping (well, maybe methods can be assigned this way, ok), because hex's properties are changing all the time, at least its "isWalkable" and "occupant".

**Comment by flauwekeul** [comment]
If you want to check the state of a hex at runtime, the only way is to use functions (or [getters/setters](https://developer.mozilla.org/nl/docs/Web/JavaScript/Guide/Working_with_Objects#Defining_getters_and_setters), but that gets smelly very fast):

```js
var grid = Honeycomb.Grid({
    isWalkable: function isWalkable() {
        // logic to determine if the hex (?) is walkable
    },
    // I prefer factory methods for creating objects...
    occupant: Occupant({
        type: 'Peon',
        health: 100,
        isAlive: function isAlive() {
            return this.health > 0;
        },
        onClick: function onClick() {
            console.log('Yesh me lord');
        }
    })
});

function Occupant(settings) {
    // returns an object with `settings` as its prototype
    return Object.create(settings);
}
```

I don't see how Honeycomb can help with this...But again: ideas are welcome.

**Comment by ayahnenko** [comment]
The occupant is not anyhow related to the hex itself, it will always be an instance of subclass of the GameObject class, like Unit, Building, etc.
Putting it or any of its logic into the hex will be wrong design.

Actually, I already have almost all of the game logic implemented, and I have a working map.
But now my goal is to migrate to hex-based map.

So again - the Honeycomb is great for generating grids, and doing hex-related calculations, but not for working with grid as a live map (at least now). That is why I'm going to have it as a calculator, implanted into my map and I will implement all the game logic in this map.

Thanks again for your help :)

**Comment by flauwekeul** [comment]
It's probably best to wrap the grid instance and/or hexes in your own functions/objects. Separation of concern and all that 🤓

It was a pleasure having this discussion. Thanks for your input!
